#pragma once

// Define kernel mode macro to trigger correct includes in api.h
#define _IS_KERNEL_MODE_COMPONENT 1

// Include Kernel Frameworks
extern "C" {
#include <ntddk.h>
#include <wdf.h>
#include <usb.h>
#include <usbdlib.h>
#include <usbioctl.h>
}

// Include shared definitions
#include "api.h"

// Internal NT device name used by the object manager.
DECLARE_CONST_UNICODE_STRING(ntDeviceName, L"\\Device\\BusFilterIOCTL");

// Symbolic link exposed to the Win32 subsystem so user-mode apps can call CreateFileW.
DECLARE_CONST_UNICODE_STRING(symbolicLinkName, L"\\Global??\\BusFilterIOCTL");

// ============================================================================
// Internal Kernel-Mode Data Structures
// ============================================================================
// These structures track state and synchronization within the driver memory pool.

// Context for the global control device that handles communication with the user app.
typedef struct _CONTROL_DEVICE_CONTEXT {
    // A WDF manual dispatch queue. Holds IOCTL_CUSTOM_GET_EVENT requests indefinitely 
    // until the filter intercepts an event and completes a request with data.
    WDFQUEUE NotificationQueue;
} CONTROL_DEVICE_CONTEXT, * PCONTROL_DEVICE_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(CONTROL_DEVICE_CONTEXT, GetControlContext)

// Master context tied to the WDFDRIVER object.
typedef struct _DRIVER_CONTEXT {
    // Head of a global linked list containing all active child filter extensions.
    LIST_ENTRY FilterDeviceListHead;

    // Global spinlock to synchronize thread access when inserting or removing items 
    // from the FilterDeviceListHead.
    WDFSPINLOCK FilterDeviceLock;

    // Security flag to indicate if a user-mode application holds an open handle.
    // If FALSE, the driver will not intercept or queue incoming URBs.
    volatile BOOLEAN IsAppConnected;
} DRIVER_CONTEXT, * PDRIVER_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DRIVER_CONTEXT, GetDriverContext)

// Maps an opaque USBD_PIPE_HANDLE from an URB to a physical endpoint address.
typedef struct _PIPE_MAPPING_ENTRY {
    // The handle generated by the lower USB stack during device configuration.
    USBD_PIPE_HANDLE PipeHandle;

    // The actual physical address of the endpoint (e.g., 0x81).
    UCHAR EndpointAddress;

    // The interface the endpoint belongs to.
    UCHAR InterfaceNumber;

    // TRUE if this slot in the array contains active mapping data.
    BOOLEAN IsValid;
} PIPE_MAPPING_ENTRY, * PPIPE_MAPPING_ENTRY;

// Tracking structure allocated for each URB intercepted and held by the driver.
typedef struct _PENDING_IRP_EVENT {
    // Linked list node to insert this struct into the device's pending event queue.
    LIST_ENTRY ListEntry;

    // Pointer to the suspended I/O Request Packet.
    PIRP Irp;

    // The u
    // nique identifier sent to user mode for this specific IRP.
    UINT64 EventId;

    // Direct pointer to the mapped, kernel-safe data buffer of the URB.
    PVOID rawBuffer;

    // Total size of the rawBuffer in bytes. Used when clearing memory for denied requests.
    ULONG urbDataLength;
} PENDING_IRP_EVENT, * PPENDING_IRP_EVENT;

// Device extension for the raw WDM filter devices attached to individual USB peripherals.
typedef struct _CHILD_FILTER_EXTENSION {
    // Identifier to confirm this structure is our WDM filter before casting.
    ULONG MagicNumber;

    // Secondary boolean verification that this is the WDM interceptor.
    BOOLEAN IsWdmFilter;

    // Pointer to the next device object down in the USB stack. We forward unhandled IRPs here.
    PDEVICE_OBJECT LowerDevice;

    // The Physical Device Object created by the underlying bus.
    PDEVICE_OBJECT Pdo;

    // Pointer to the filter device object itself.
    PDEVICE_OBJECT WdmDeviceObject;

    // Node for inserting this filter extension into the global DRIVER_CONTEXT list.
    LIST_ENTRY GlobalListEntry;

    // Head of the linked list holding all PENDING_IRP_EVENT structures for this specific device.
    LIST_ENTRY PendingEventListHead;

    // Spinlock to synchronize access when adding/removing/canceling IRPs in PendingEventListHead.
    KSPIN_LOCK EventListLock;

    // Atomic counter used to generate sequential EventIds for intercepted URBs.
    volatile LONG64 NextEventId;

    // Spinlock to synchronize access to the PipeMappings array.
    KSPIN_LOCK PipeMappingLock;

    // The physical USB port number the device is plugged into (queried from PnP properties).
    ULONG PortNumber;

    // Contains Product ID and Vendor ID 
    PWCHAR HardwareIDs;
    ULONG HardwareIDsLength;

    // Broad Identifiers for device class
    PWCHAR CompatibleIDs;
    ULONG CompatibleIDsLength;

    // Child Devices belonging to a composite device share a container ID 
    PWCHAR ContainerId;
    ULONG ContainerIdLength;

    // Set to true after the user mode requests to remove a device
    BOOLEAN IsBanned;

    // Array holding mapping data to resolve USBD_PIPE_HANDLEs to endpoint addresses.
    PIPE_MAPPING_ENTRY PipeMappings[MAX_SUPPORTED_PIPES];
} CHILD_FILTER_EXTENSION, * PCHILD_FILTER_EXTENSION;

// ============================================================================
// Forward Function Declarations
// ============================================================================

extern "C" {
    // Driver entry point.
    DRIVER_INITIALIZE DriverEntry;
}

// ----------------------------------------------------------------------------
// WDF Callbacks
// ----------------------------------------------------------------------------
EVT_WDF_DRIVER_DEVICE_ADD HubFilterEvtDeviceAdd;
EVT_WDF_DRIVER_UNLOAD BusFilterDriverEvtDriverUnload;
EVT_WDFDEVICE_WDM_IRP_PREPROCESS HubFilter_WdmPnpPreprocess;

// ----------------------------------------------------------------------------
// Control Device Callbacks (User-Mode Interaction)
// ----------------------------------------------------------------------------

// Declare the worker routine
extern "C" {
    IO_WORKITEM_ROUTINE DeferredUrbNotifyCallback;
}

// Used to provide the DeferredUrbNotifyCallback with the necessary context to 
// notify the user mode application asynchronously 
typedef struct _URB_NOTIFY_CONTEXT {
    PIO_WORKITEM WorkItem;
    PCHILD_FILTER_EXTENSION Ext;
    PBUSFILTER_EVENT_PACKET Packet;
    size_t PacketSize;
    UINT64 EventId;
} URB_NOTIFY_CONTEXT, * PURB_NOTIFY_CONTEXT;

EVT_WDF_DEVICE_FILE_CREATE ControlDeviceEvtFileCreate;
EVT_WDF_FILE_CLEANUP ControlDeviceEvtFileCleanup;

// Dispatches IOCTL requests from user space.
VOID InvertedIoDeviceControl(
    WDFQUEUE Queue,
    WDFREQUEST Request,
    size_t OutputBufferLength,
    size_t InputBufferLength,
    ULONG IoControlCode
);

// Pushes an event packet to a pending IOCTL in the NotificationQueue.
NTSTATUS InvertedEventNotify(
    _In_ PBUSFILTER_EVENT_PACKET EventPacket,
    _In_ size_t PacketSize
);

// ----------------------------------------------------------------------------
// WDM Filter Callbacks & Dispatch
// ----------------------------------------------------------------------------

// Global dispatch routine hooked into the WDM dispatch table. Routes traffic.
NTSTATUS ChildFilter_GlobalDispatch(
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
);

// Handles PnP state changes for intercepted hardware.
NTSTATUS ChildFilter_DispatchPnp(
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
);

// Intercepts URBs submitted via internal device control IRPs.
NTSTATUS ChildFilter_DispatchInternalDeviceControl(
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
);

// Completion routine triggered when bus enumeration creates new PDOs.
IO_COMPLETION_ROUTINE HubFilter_BusRelationsCompletion;

// Completion routine triggered when the USB stack finishes fulfilling a URB.
IO_COMPLETION_ROUTINE ChildFilter_UrbCompletionRoutine;

// The lower drivers would modify the changes to the IRP ChildFilter_DispatchPnp made inside ChildFilter_PnpSynchronousCompletion
// This function notifies ChildFilter_DispatchPnp upon completion and allows it to perform further operations on the IRP
IO_COMPLETION_ROUTINE ChildFilter_PnpSynchronousCompletion;

// System cancel routine executed if the OS attempts to cancel a held IRP.
VOID ChildFilter_CancelHeldIrp(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp
);

// ----------------------------------------------------------------------------
// Buffer and Endpoint Helpers
// ----------------------------------------------------------------------------

// Resolves a transfer buffer to a safe kernel address, verifying MDL mappings.
PVOID Helper_GetUsableBuffer(
    _In_ PMDL Mdl,
    _In_ PVOID TransferBuffer
);

// Helper to dynamically query variable-length device properties
PWCHAR
Helper_QueryDevicePropertyString(
    _In_ PDEVICE_OBJECT Pdo,
    _In_ DEVICE_REGISTRY_PROPERTY DeviceProperty,
    _Out_ PULONG OutLength
);

// Extracts the underlying buffer properties from the opaque URB structures.
_Success_(return != FALSE)
BOOLEAN Helper_ExtractUrbDataParameters(
    _In_ PURB Urb,
    _Out_ PVOID * TransferBuffer,
    _Out_ PMDL * TransferBufferMDL,
    _Out_ PULONG TransferBufferLength,
    _Out_ USBD_PIPE_HANDLE * EndpointHandle
);

// Caches the association between a pipe handle and its endpoint address.
VOID Helper_SavePipeMapping(
    _In_ PCHILD_FILTER_EXTENSION Ext,
    _In_ USBD_PIPE_HANDLE PipeHandle,
    _In_ UCHAR EndpointAddress,
    _In_ UCHAR InterfaceNumber
);

// Retrieves the endpoint address associated with a pipe handle.
BOOLEAN Helper_GetEndpointFromPipeHandle(
    _In_ PCHILD_FILTER_EXTENSION Ext,
    _In_ USBD_PIPE_HANDLE PipeHandle,
    _Out_ PUCHAR EndpointAddress
);
